### PR TITLE
reversed the opinion on splitting monorepo based on personal experiences

### PR DESCRIPTION
**Pull request by sifangli-labs**

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Can you say more about this pull request, such as your experiences and the purpose of the commit?

**Comment by sifangli-labs** [comment]
Here are some background info. 
Before my current job, I had previously worked in more than a dozen companies - only two of them (more recent) used monorepo/bazel. By the time I joined, they were 2-4 yrs old and huge in size. What I noticed is that we could easily incorporate new repos into the mono repo by expanding the code base tree. Also, no matter how much bazel trouble we had, no one attempt or even discuss to separate the mono-repo into smaller ones - I felt part of it was considered mission impossible due to monrepo does not foster a clean arch/design - things were very much connected. I am very surprised to the oppsiting opinions described in this repo. 
I think an analogy to this problem I can think of is that is it is easier to add code and much difficult to remove code from a existing code base.

**Comment by joelparkerhenderson** [comment]
Thank you for the specifics. What I'd like to do is add your perspective as a counterpoint, rather than replacing the original text. If you can write more about your experience too, that's great because you can help more people.

For example...

- How big are the monorepos that you're describing?  For example, number of projects, or number of programming languages, or nodes in the dependency graph, or count of files, etc.? (The purpose of this item is to help readers understand the overall high-level complexity)

- How are the monorepos arranged? For example, by team, or by project, or by language, or by package, or by microservice, etc.? (The purpose of this item is to help readers understand the high-level organizational complexity)

- What problems are happening with bazel? Were there also any problems with the repo independent of bazel, such as poor checkouts, merge conflicts, slowness of updates, hosting troubles, etc.? (The purpose of this item is to help readers understand the pain points of bazel versus the pain points of a monorepo itself)

- What's the organization of the people generally like, such as a high tech startup with small squads building customer-facing mobile apps, or an enterprise manufacturing company with 100+ person teams building physical devices, or midsize SaaS provider building customer-specific builds, etc.? (The purpose of this item is to look for Conway's Law areas; Conway's law loosely says “Organizations tend to produce designs which are copies of the communication structures").

**Comment by joelparkerhenderson** [comment]
I haven't seen a reply from you in a couple of weeks, so I'll close this as inactive. If you want, you're welcome to re-open it with more information. Thank you.

**Pull request closed without merging**
